Add Sourceforge upload = 3rd pass [build pkg]

diff --git a/builds/utilities/ci/travis/prepare_store b/builds/utilities/ci/travis/prepare_store
--- a/builds/utilities/ci/travis/prepare_store
+++ b/builds/utilities/ci/travis/prepare_store
@@ -8,7 +8,11 @@
 #
 cd $LP3D_BUILD_FOLDER
 
-chmod +x "${LP3D_CI_DIR}/dropbox_uploader.sh";
-echo $(./"${LP3D_CI_DIR}/dropbox_uploader.sh" list "$LP3D_DROPBOX_RELEASES_DIR") | grep -w 'DONE' \
-&& echo "Deleting old Dropbox store folder '$LP3D_DROPBOX_RELEASES_DIR'..." \
-&& ./"${LP3D_CI_DIR}/dropbox_uploader.sh" delete "$LP3D_DROPBOX_RELEASES_DIR" || true
+if [ -f "/tmp/.dropbox_oauth" ]; then
+  chmod +x "${LP3D_CI_DIR}/dropbox_uploader.sh";
+  echo $(./"${LP3D_CI_DIR}"/dropbox_uploader.sh list "$LP3D_DROPBOX_RELEASES_DIR") | grep -w 'DONE' \
+  && echo "Deleting old Dropbox store folder '$LP3D_DROPBOX_RELEASES_DIR'..." \
+  && ./"${LP3D_CI_DIR}/dropbox_uploader.sh" delete "$LP3D_DROPBOX_RELEASES_DIR" || true
+else
+  echo "ERROR - /tmp/.dropbox_oauth not found - cannot perform delete.";
+fi;
